Importing the Libraries

In [ ]:
import spacy
import nltk
import gensim
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk import ngrams
from sklearn import preprocessing #scikit-learn

In [ ]:
##LOWERCASE Pre-processing

text_data = """
Let's convert this demo text to Lowercase for this NLP Tutorial using NLTK. NLTK stands for Natural Language Toolkit
"""
lower_text = text_data.lower()
print (lower_text)


let's convert this demo text to lowercase for this nlp tutorial using nltk. nltk stands for natural language toolkit



In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
word_tokens = word_tokenize(text_data)
print(word_tokens)

['Let', "'s", 'convert', 'this', 'demo', 'text', 'to', 'Lowercase', 'for', 'this', 'NLP', 'Tutorial', 'using', 'NLTK', '.', 'NLTK', 'stands', 'for', 'Natural', 'Language', 'Toolkit']


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
stopword = stopwords.words('english')
removing_stopwords = [word for word in word_tokens if word not in stopword]
print (removing_stopwords)

['Let', "'s", 'convert', 'demo', 'text', 'Lowercase', 'NLP', 'Tutorial', 'using', 'NLTK', '.', 'NLTK', 'stands', 'Natural', 'Language', 'Toolkit']


In [ ]:
ps = PorterStemmer() #most commonly used stemmers
stemmed_words = [ps.stem(word) for word in word_tokens]
print(stemmed_words)

['let', "'s", 'convert', 'thi', 'demo', 'text', 'to', 'lowercas', 'for', 'thi', 'nlp', 'tutori', 'use', 'nltk', '.', 'nltk', 'stand', 'for', 'natur', 'languag', 'toolkit']


In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
wnl = WordNetLemmatizer()
word_tokens2 = ["corpora","better","rocks","caring","classes"]
lemmatized_word = [wnl.lemmatize(word)
for word in word_tokens2]
print (lemmatized_word)

['corpus', 'better', 'rock', 'caring', 'class']


Let's convert this demo text to Lowercase for this NLP Tutorial using NLTK. NLTK stands for Natural Language Toolkit

In [ ]:
n_grams = ngrams(text_data.split(), 3)
for grams in n_grams:
  print(grams)

("Let's", 'convert', 'this')
('convert', 'this', 'demo')
('this', 'demo', 'text')
('demo', 'text', 'to')
('text', 'to', 'Lowercase')
('to', 'Lowercase', 'for')
('Lowercase', 'for', 'this')
('for', 'this', 'NLP')
('this', 'NLP', 'Tutorial')
('NLP', 'Tutorial', 'using')
('Tutorial', 'using', 'NLTK.')
('using', 'NLTK.', 'NLTK')
('NLTK.', 'NLTK', 'stands')
('NLTK', 'stands', 'for')
('stands', 'for', 'Natural')
('for', 'Natural', 'Language')
('Natural', 'Language', 'Toolkit')


## **Word Vectorization**

## **One Hot Vector Encoding**

In [ ]:
word_tokens3 = ['corpora', 'better', 'rocks', 'care', 'classes','better','apple']
lab_encoder = preprocessing.LabelEncoder()
int_label_encoder = lab_encoder.fit_transform(word_tokens3)
lab_encoded = int_label_encoder.reshape(len(int_label_encoder),1)
one_hot_encoder = preprocessing.OneHotEncoder(sparse=False)
one_hot_encoded = one_hot_encoder.fit_transform(lab_encoded)
print(one_hot_encoded)
print(word_tokens3)

[[0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
['corpora', 'better', 'rocks', 'care', 'classes', 'better', 'apple']


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## NAMED ENTITY RECOGNITION

In [ ]:
nlp = spacy.load("en_core_web_sm")
# Process whole documents
text = ("When Sebastian Thrun started working on self-driving cars at "
"Google in 2007, few people outside of the company took him "
"seriously. “I can tell you very senior CEOs of major American "
"car companies would shake my hand and turn away because I wasn’t "
"worth talking to,” said Thrun, in an interview with Recode earlier "
"this week.")
doc = nlp(text)

# Find named entities, phrases and concepts
for entity in doc.ents:
  print(entity.text, entity.label_)

Sebastian Thrun PERSON
Google ORG
2007 DATE
American NORP
Thrun PERSON
Recode ORG
earlier this week DATE
