In [ ]:
import numpy as np

arr = np.array ([[1, 2, 3],
                 [4, 5, 6]])

print(arr)

#type of array

print("Array of the type: ", type(arr))

# dimensions

print("No. of dimensions: ", arr.ndim)

# Shape

print("Shape of array: ", arr.shape)

# Size

print("Size of array: ", arr.size)

[[1 2 3]
 [4 5 6]]
Array of the type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


In [ ]:
arr_1 = np.array((5, 6, 7))

print(arr_1)

[5 6 7]


In [ ]:
arr_2 = np.array([10, 11, 12])

print(arr_2)

[10 11 12]


In [ ]:
#Array creation using array function

#array(data type, value list)

import array

arr_3 = array.array('i', [3, 4, 5])

print("The created array is: ", arr_3)

The created array is:  array('i', [3, 4, 5])


In [ ]:
#np.zeros

A = np.zeros([2, 3], dtype = int)
print("\nMatrix A: \n", A)


Matrix A: 
 [[0 0 0]
 [0 0 0]]


In [ ]:
#np.zeros

B = np.zeros([3, 3], dtype = int)
print("\nMatrix B: \n", B)


Matrix B: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#np.ones

C = np.ones([3, 3], dtype = int)
print("\nMatrix C: \n", C)


Matrix C: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#np.empty

D = np.empty([3, 3], dtype = int)
print("\nMatrix D: \n", D)


Matrix D: 
 [[102224002359834               0               0]
 [              0               0               0]
 [              0               0               0]]


In [ ]:
# range

for i in range(4):
  print (i)

0
1
2
3


In [ ]:
#numpy.arange

array_1 = np.arange(8)

print("Original Array: ", array_1)

Original Array:  [0 1 2 3 4 5 6 7]


In [ ]:
#shape array with 2 rows and 4 columns

array_1 = np.arange(8).reshape(2, 4)

print("\nReshaped Array: \n", array_1)


Reshaped Array: 
 [[0 1 2 3]
 [4 5 6 7]]


In [ ]:
array_1=np.arange(8).reshape(2, 2, 2)

In [ ]:
print("\nReshaped Array: \n", array_1)


Reshaped Array: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#arange(start, stop, step)

print("A\n", np.arange(4, 20, 2), "\n")

A
 [ 4  6  8 10 12 14 16 18] 



In [ ]:
#numpy.linspace

x = np.linspace(0, 2, 10)
print("A\n", np.sin(x))

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [ ]:
p = np.array([[1, 2], [3, 4]])
q = np.array([[5, 6], [7, 8]])

print("Matrix p: ")
print(p)
print("Matrix q: ")
print(q)

Matrix p: 
[[1 2]
 [3 4]]
Matrix q: 
[[5 6]
 [7 8]]


In [ ]:
result = np.dot(p, q)
print(result)

[[19 22]
 [43 50]]


In [ ]:
print(np.add(p, q))

[[ 6  8]
 [10 12]]


In [ ]:
print(np.subtract(q, p))

[[4 4]
 [4 4]]


In [ ]:
#Scalar Product

import matplotlib.pyplot as plt
import math

v = np.array([4, 3, 2])

w = 5 * v

print("\nw: \n", w)


w: 
 [20 15 10]


In [ ]:
print(p)

[[1 2]
 [3 4]]


In [ ]:
print(q)

[[5 6]
 [7 8]]


In [ ]:
r = np.cross(p, q)

print(r)

[-4 -4]
